export const REQUEST_TYPES = ['Create Driver', 'Modify Driver', 'Disable Driver'];

export const DRIVER_FIELDS = [
  {
    key: 'username',
    label: 'Username',
    autoGenerated: true,
    note: 'Username is assigned automatically by AD in the format firstname.lastname@asmo.com',
  },
  { key: 'firstName', label: 'First Name', required: true },
  { key: 'lastName', label: 'Last Name', required: true },
  { key: 'email', label: 'Email Address', required: true },
  { key: 'phone', label: 'Mobile Number', required: true },
  { key: 'role', label: 'Role', fixed: true, defaultValue: 'Privileged User' },
  { key: 'customerGroup', label: 'Group / Customer', placeholder: 'e.g. CUEU/ARCO', required: true },
  { key: 'driverClass', label: 'Driver Class', placeholder: 'e.g. 30Ton_Drivers', required: true},
  { key: 'operatingHours', label: 'Operating Hours', required: true},
  { key: 'poNumber', label: 'PO Number', required: true},
  { key: 'poExpiry', label: 'PO Expiry Date', type: 'date', required: true},
];

export const EMPTY_DRIVER = DRIVER_FIELDS.reduce((acc, f) => {
  acc[f.key] = f.defaultValue || '';
  return acc;
}, {});

export const MAX_DRIVERS = 100;
