export const REQUEST_TYPES = ['Create Driver', 'Modify Driver', 'Disable Driver'];

export const DRIVER_FIELDS = [
  {
    key: 'username',
    label: 'Username',
    autoGenerated: true,
    note: 'Username is assigned automatically by AD in the format firstname.lastname@asmo.com',
  },
  { key: 'role', label: 'Role', fixed: true, defaultValue: 'Privileged User' },
  { key: 'firstName', label: 'First Name', required: true },
  { key: 'lastName', label: 'Last Name', required: true },
  { key: 'email', label: 'Email Address', required: true },
  { key: 'phone', label: 'Mobile Number', required: true },
  { key: 'customerGroup', label: 'Group / Customer', placeholder: 'e.g. CUEU/ARCO', required: true, hiddenFromRequester: true },
  { key: 'driverClass', label: 'Driver Class', placeholder: 'e.g. 30Ton_Drivers', required: true, hiddenFromRequester: true },
  { key: 'operatingHours', label: 'Operating Hours', required: true, hiddenFromRequester: true },
  { key: 'poNumber', label: 'PO Number', required: true},
  { key: 'poExpiry', label: 'PO Expiry Date', type: 'date', required: true},
  { key: 'city', label: 'Driver City (CR)', placeholder: 'Select or enter city', required: true, createOnly: true, suggestions: ['Khobar', 'Riyadh', 'Jeddah', 'Dammam'] },
  { key: 'licenseNumber', label: 'Driver License Number (CR)', placeholder: 'Enter driver license number', required: true, createOnly: true },
  { key: 'licenseExpiry', label: 'Driver License Expiration Date (CR)', type: 'date', required: true, createOnly: true },
  { key: 'hasInsurance', label: 'Driver/Car Insurance (CR)', type: 'select', options: ['Yes', 'No'], required: true, createOnly: true },
  { key: 'licenseFile', label: 'Driver License', type: 'file', accept: '.pdf,.jpg,.jpeg,.png', required: true, createOnly: true },
  { key: 'idFile', label: 'Driver ID', type: 'file', accept: '.pdf,.jpg,.jpeg,.png', required: true, createOnly: true },
  { key: 'photoFile', label: 'Driver Photo', type: 'file', accept: '.jpg,.jpeg,.png', required: true, createOnly: true },
];

export const EMPTY_DRIVER = DRIVER_FIELDS.reduce((acc, f) => {
  acc[f.key] = f.defaultValue || '';
  return acc;
}, {});

export const MAX_DRIVERS = 1000;
