import { DRIVER_FIELDS, EMPTY_DRIVER, MAX_DRIVERS } from '../../utils/constants.js';
import OperatingHoursPicker from './OperatingHoursPicker.jsx';

/**
 * Editable table for manually adding driver rows to a request.
 * `drivers` / `setDrivers` are lifted state from the parent (NewRequest page).
 */
export default function DriverTable({ drivers, setDrivers, readOnly = false }) {
  const hasChangeSummaries = readOnly && drivers.some((d) => d.changeSummary);
  const hasDriverStatus = readOnly && drivers.some((d) => d.driverStatus);
  // Username is assigned by AD after the fact, so it's not a field the
  // requester fills in - only show that column once a value actually exists.
  const visibleFields = DRIVER_FIELDS.filter((f) => readOnly || !f.autoGenerated);
  function addRow() {
    if (drivers.length >= MAX_DRIVERS) return;
    setDrivers([...drivers, { ...EMPTY_DRIVER }]);
  }

  function removeRow(idx) {
    setDrivers(drivers.filter((_, i) => i !== idx));
  }

  function updateCell(idx, key, value) {
    const next = drivers.slice();
    next[idx] = { ...next[idx], [key]: value };
    setDrivers(next);
  }

  function removeAll() {
    setDrivers([]);
  }

  return (
    <div className="border border-gray-200 rounded-lg overflow-hidden">
      {!readOnly && (
        <div className="flex justify-end gap-2 bg-gray-50 px-4 py-2 border-b border-gray-200">
          <button
            type="button"
            onClick={removeAll}
            disabled={!drivers.length}
            className="text-sm px-3 py-1.5 rounded-md border border-gray-300 text-gray-600 disabled:opacity-40 hover:bg-gray-100"
          >
            Remove All
          </button>
          <button
            type="button"
            onClick={addRow}
            disabled={drivers.length >= MAX_DRIVERS}
            className="text-sm px-3 py-1.5 rounded-md bg-primary-600 text-white hover:bg-primary-700 disabled:opacity-40"
          >
            + Add Driver
          </button>
        </div>
      )}
      {!readOnly && (
        <p className="text-xs text-gray-500 px-4 pt-3">
          Username will be assigned automatically by AD in the format{' '}
          <span className="font-medium">firstname.lastname@asmo.com</span>.
        </p>
      )}
      <div className="overflow-x-auto">
        <table className="min-w-full text-sm">
          <thead className="bg-gray-50 text-gray-600">
            <tr>
              {!readOnly && <th className="px-3 py-2 text-left w-10">#</th>}
              {visibleFields.map((f) => (
                <th key={f.key} className="px-3 py-2 text-left font-medium whitespace-nowrap">
                  {f.label}
                  {f.required && <span className="text-red-500">*</span>}
                </th>
              ))}
              {hasDriverStatus && <th className="px-3 py-2 text-left font-medium whitespace-nowrap">Request Status</th>}
              {hasChangeSummaries && <th className="px-3 py-2 text-left font-medium whitespace-nowrap">Changes</th>}
              {!readOnly && <th className="px-3 py-2 w-10" />}
            </tr>
          </thead>
          <tbody>
            {drivers.length === 0 && (
              <tr>
                <td
                  colSpan={visibleFields.length + 2 + (hasDriverStatus ? 1 : 0) + (hasChangeSummaries ? 1 : 0)}
                  className="text-center text-gray-400 py-8"
                >
                  No data to display
                </td>
              </tr>
            )}
            {drivers.map((row, idx) => (
              <tr key={idx} className="border-t border-gray-100">
                {!readOnly && <td className="px-3 py-2 text-gray-400">{idx + 1}</td>}
                {visibleFields.map((f) => (
                  <td key={f.key} className="px-2 py-1.5">
                    {readOnly || f.fixed ? (
                      <span className="whitespace-nowrap">{row[f.key] || f.defaultValue || '-'}</span>
                    ) : f.key === 'operatingHours' ? (
                      <div className="min-w-[240px]">
                        <OperatingHoursPicker value={row[f.key]} onChange={(v) => updateCell(idx, f.key, v)} />
                      </div>
                    ) : (
                      <input
                        type={f.type || 'text'}
                        value={row[f.key] || ''}
                        placeholder={f.placeholder || ''}
                        onChange={(e) => updateCell(idx, f.key, e.target.value)}
                        className="w-36 border border-gray-200 rounded px-2 py-1 text-sm focus:outline-none focus:ring-1 focus:ring-primary-500"
                      />
                    )}
                  </td>
                ))}
                {hasDriverStatus && (
                  <td className="px-3 py-2 whitespace-nowrap">
                    <span className="px-2 py-0.5 rounded-full text-xs bg-orange-100 text-orange-700">
                      {row.driverStatus || '-'}
                    </span>
                  </td>
                )}
                {hasChangeSummaries && (
                  <td className="px-3 py-2 text-xs text-gray-600 max-w-xs">
                    {row.changeSummary || <span className="text-gray-300">No changes</span>}
                  </td>
                )}
                {!readOnly && (
                  <td className="px-3 py-2">
                    <button
                      type="button"
                      onClick={() => removeRow(idx)}
                      className="text-red-500 hover:text-red-700"
                      aria-label="Remove row"
                    >
                      ✕
                    </button>
                  </td>
                )}
              </tr>
            ))}
          </tbody>
        </table>
      </div>
    </div>
  );
}
