import { useState } from 'react';
import { DRIVER_FIELDS, EMPTY_DRIVER, MAX_DRIVERS } from '../../utils/constants.js';
import { validateField } from '../../utils/validators.js';
import OperatingHoursPicker from './OperatingHoursPicker.jsx';

/**
 * Editable table for manually adding driver rows to a request.
 * `drivers` / `setDrivers` are lifted state from the parent (NewRequest page).
 */
export default function DriverTable({
  drivers,
  setDrivers,
  readOnly = false,
  filesEditable,
  forceValidate = false,
  skipFileRequiredValidation = false,
  showOperationsFields = false,
}) {
  const canEditFiles = filesEditable ?? !readOnly;
  const [touched, setTouched] = useState({});

  const hasChangeSummaries = readOnly && drivers.some((d) => d.changeSummary);
  const hasDriverStatus = readOnly && drivers.some((d) => d.driverStatus);
  // Username is assigned by AD after the fact, so it's not a field the
  // requester fills in - only show that column once a value actually exists.
  // The three Operations-only fields (Group/Customer, Driver Class,
  // Operating Hours) are never shown to requesters - they are completed by
  // Operations during the Processing stage, and staff-facing views opt in
  // via showOperationsFields. Document uploads are shown inline only while
  // editing - completed requests list them via AttachmentsList instead.
  const visibleFields = DRIVER_FIELDS.filter((f) => {
    if (f.autoGenerated) return readOnly;
    if (f.hiddenFromRequester && !showOperationsFields) return false;
    if (f.hiddenFromRequester && !readOnly) return false;
    if (f.type === 'file' && readOnly) return false;
    return true;
  });

  function addRow() {
    if (drivers.length >= MAX_DRIVERS) return;
    setDrivers([...drivers, { ...EMPTY_DRIVER }]);
  }

  function removeRow(idx) {
    setDrivers(drivers.filter((_, i) => i !== idx));
  }

  function updateCell(idx, key, value) {
    const next = drivers.slice();
    next[idx] = { ...next[idx], [key]: value };
    setDrivers(next);
  }

  function removeAll() {
    setDrivers([]);
  }

  function markTouched(idx, key) {
    setTouched((prev) => ({ ...prev, [`${idx}:${key}`]: true }));
  }

  function cellError(idx, f, row) {
    if (readOnly) return null;
    // Editing a returned request doesn't re-populate file inputs (browsers
    // won't let us pre-fill them from an existing upload) - the original
    // documents are still attached server-side, so don't force a re-upload.
    if (skipFileRequiredValidation && f.type === 'file') return null;
    const isTouched = forceValidate || touched[`${idx}:${f.key}`];
    if (!isTouched) return null;
    return validateField(f, row[f.key], { requireCreateFields: true });
  }

  return (
    <div className="border border-gray-200 rounded-lg overflow-hidden">
      {!readOnly && (
        <div className="flex justify-end gap-2 bg-gray-50 px-4 py-2 border-b border-gray-200">
          <button
            type="button"
            onClick={removeAll}
            disabled={!drivers.length}
            className="text-sm px-3 py-1.5 rounded-md border border-gray-300 text-gray-600 disabled:opacity-40 hover:bg-gray-100"
          >
            Remove All
          </button>
          <button
            type="button"
            onClick={addRow}
            disabled={drivers.length >= MAX_DRIVERS}
            className="text-sm px-3 py-1.5 rounded-md bg-primary-600 text-white hover:bg-primary-700 disabled:opacity-40"
          >
            + Add Driver
          </button>
        </div>
      )}
      {!readOnly && (
        <p className="text-xs text-gray-500 px-4 pt-3">
          Username will be assigned automatically by AD in the format{' '}
          <span className="font-medium">firstname.lastname@asmo.com</span>.
        </p>
      )}
      <div className="overflow-x-auto">
        <table className="min-w-full text-sm">
          <thead className="bg-gray-50 text-gray-600">
            <tr>
              {!readOnly && <th className="px-3 py-2 text-left w-10">#</th>}
              {visibleFields.map((f) => (
                <th key={f.key} className="px-3 py-2 text-left font-medium whitespace-nowrap">
                  {f.label}
                  {f.required && <span className="text-red-500">*</span>}
                </th>
              ))}
              {hasDriverStatus && <th className="px-3 py-2 text-left font-medium whitespace-nowrap">Request Status</th>}
              {hasChangeSummaries && <th className="px-3 py-2 text-left font-medium whitespace-nowrap">Changes</th>}
              {!readOnly && <th className="px-3 py-2 w-10" />}
            </tr>
          </thead>
          <tbody>
            {drivers.length === 0 && (
              <tr>
                <td
                  colSpan={visibleFields.length + 2 + (hasDriverStatus ? 1 : 0) + (hasChangeSummaries ? 1 : 0)}
                  className="text-center text-gray-400 py-8"
                >
                  No data to display
                </td>
              </tr>
            )}
            {drivers.map((row, idx) => (
              <tr key={idx} className="border-t border-gray-100 align-top">
                {!readOnly && <td className="px-3 py-2 text-gray-400">{idx + 1}</td>}
                {visibleFields.map((f) => {
                  const error = cellError(idx, f, row);
                  const inputBorder = error ? 'border-red-400' : 'border-gray-200';

                  return (
                    <td key={f.key} className="px-2 py-1.5">
                      {readOnly || f.fixed ? (
                        <span className="whitespace-nowrap">
                          {f.type === 'file'
                            ? row[f.key]?.name || '-'
                            : row[f.key] || f.defaultValue || '-'}
                        </span>
                      ) : f.key === 'operatingHours' ? (
                        <div className="min-w-[240px]">
                          <OperatingHoursPicker value={row[f.key]} onChange={(v) => updateCell(idx, f.key, v)} />
                        </div>
                      ) : f.type === 'select' ? (
                        <div>
                          <select
                            required={f.required}
                            value={row[f.key] || ''}
                            onChange={(e) => updateCell(idx, f.key, e.target.value)}
                            onBlur={() => markTouched(idx, f.key)}
                            className={`w-32 border rounded px-2 py-1 text-sm focus:outline-none focus:ring-1 focus:ring-primary-500 ${inputBorder}`}
                          >
                            <option value="">Select...</option>
                            {f.options.map((opt) => (
                              <option key={opt} value={opt}>
                                {opt}
                              </option>
                            ))}
                          </select>
                          {error && <p className="text-[11px] text-red-500 mt-0.5">{error}</p>}
                        </div>
                      ) : f.type === 'file' ? (
                        <div className="min-w-[140px]">
                          {row[f.key] ? (
                            <div className="flex items-center justify-between gap-1 text-xs bg-gray-50 rounded px-2 py-1">
                              <span className="truncate">📎 {row[f.key].name}</span>
                              {canEditFiles && (
                                <button
                                  type="button"
                                  onClick={() => {
                                    updateCell(idx, f.key, '');
                                    markTouched(idx, f.key);
                                  }}
                                  className="text-red-500 hover:text-red-700 shrink-0"
                                  aria-label={`Remove ${f.label}`}
                                >
                                  ✕
                                </button>
                              )}
                            </div>
                          ) : canEditFiles ? (
                            <input
                              type="file"
                              accept={f.accept}
                              onChange={(e) => {
                                const file = e.target.files[0];
                                updateCell(idx, f.key, file || '');
                                markTouched(idx, f.key);
                                e.target.value = '';
                              }}
                              className="text-xs w-32"
                            />
                          ) : (
                            <span className="text-gray-300 text-xs">-</span>
                          )}
                          {error && <p className="text-[11px] text-red-500 mt-0.5">{error}</p>}
                        </div>
                      ) : (
                        <div>
                          <input
                            type={f.type || 'text'}
                            required={f.required}
                            value={row[f.key] || ''}
                            placeholder={f.placeholder || ''}
                            list={f.suggestions ? `${f.key}-suggestions-${idx}` : undefined}
                            onChange={(e) => updateCell(idx, f.key, e.target.value)}
                            onBlur={() => markTouched(idx, f.key)}
                            className={`w-36 border rounded px-2 py-1 text-sm focus:outline-none focus:ring-1 focus:ring-primary-500 ${inputBorder}`}
                          />
                          {f.suggestions && (
                            <datalist id={`${f.key}-suggestions-${idx}`}>
                              {f.suggestions.map((s) => (
                                <option key={s} value={s} />
                              ))}
                            </datalist>
                          )}
                          {error && <p className="text-[11px] text-red-500 mt-0.5">{error}</p>}
                        </div>
                      )}
                    </td>
                  );
                })}
                {hasDriverStatus && (
                  <td className="px-3 py-2 whitespace-nowrap">
                    <span className="px-2 py-0.5 rounded-full text-xs bg-orange-100 text-orange-700">
                      {row.driverStatus || '-'}
                    </span>
                  </td>
                )}
                {hasChangeSummaries && (
                  <td className="px-3 py-2 text-xs text-gray-600 max-w-xs">
                    {row.changeSummary || <span className="text-gray-300">No changes</span>}
                  </td>
                )}
                {!readOnly && (
                  <td className="px-3 py-2">
                    <button
                      type="button"
                      onClick={() => removeRow(idx)}
                      className="text-red-500 hover:text-red-700"
                      aria-label="Remove row"
                    >
                      ✕
                    </button>
                  </td>
                )}
              </tr>
            ))}
          </tbody>
        </table>
      </div>
    </div>
  );
}
